name: remotecontrol_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  uuid: ^4.3.3
  win32: ^5.2.0
  intl: ^0.18.0
  flutter:
    sdk: flutter
  fluent_ui: ^4.8.5
  grpc:
  protobuf:
  xml: ^6.5.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.2

flutter:
  uses-material-design: true
