name: remotecontrol_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.5 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  test: ^1.24.1
dependencies:
  win32: ^5.0.5
  intl: ^0.18.0
  flutter:
    sdk: flutter
  fluent_ui: ^4.6.2
  grpc:
  protobuf:
  xml: ^6.3.0
  get: ^4.6.5

flutter:
  uses-material-design: true
